spring.application.name=UHIS-CORRESPONDENCE-SERVICE

server.port=7996

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sahilgurav8440@gmail.com
spring.mail.password=zgwfsopfdtyuqkvf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

#Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# logs
logging.file.name=D:/FinalProject-Logs/CorrespondenceModule.log